sudo: required
services:
        - docker
script:
        - docker build -f brain-server/DockerFileDev -t sushilisfine/kserver .
        - docker build -f brain-core-api/DockerFileDev -t sushilisfine/kcore .
        - docker build -f brain-zuul/DockerFileDev -t sushilisfine/kzuul .
        - docker build -f brain-auth/DockerFileDev -t sushilisfine/kauth .
        - docker build -f brain-auth/DockerFileDev -t sushilisfine/knginx .
        
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        
        - docker push sushilisfine/kserver
        - docker push sushilisfine/kcore
        - docker push sushilisfine/kzuul
        - docker push sushilisfine/kauth
        - docker push sushilisfine/knginx


deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "ap-south-1"
  app: "resopt-docker"
  env: "ResoptDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-843615263948"
  bucker_path: "resopt-docker"
          
