sudo: required
services:
        - docker
script:
        - docker build -f brain-server/DockerFileDev -t sushilisfine/pocserver .
        - docker build -f brain-core-api/DockerFileDev -t sushilisfine/poccore .
        - docker build -f brain-zuul/DockerFileDev -t sushilisfine/poczuul .
        - docker build -f brain-auth/DockerFileDev -t sushilisfine/pocauth .
        - docker build -f nginx/DockerFileDev -t sushilisfine/pocnginx .
        
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        
        - docker push sushilisfine/pocserver
        - docker push sushilisfine/poccore
        - docker push sushilisfine/poczuul
        - docker push sushilisfine/pocauth
        - docker push sushilisfine/pocnginx


deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "ap-south-1"
  app: "resopt-docker"
  env: "ResoptDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-843615263948"
  bucker_path: "resopt-docker"
          
