sudo: required
services:
        - docker
script:
        - docker build -f brain-server/DockerFileDev -t sushilisfine/pocserver:2 .
        - docker build -f brain-core-api/DockerFileDev -t sushilisfine/poccore:2 .
        - docker build -f brain-zuul/DockerFileDev -t sushilisfine/poczuul:2 .
        - docker build -f brain-auth/DockerFileDev -t sushilisfine/pocauth:2 .
        - docker build -f nginx/DockerFileDev -t sushilisfine/pocnginx:2 .

        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        
        - docker push sushilisfine/pocserver:2
        - docker push sushilisfine/poccore:2
        - docker push sushilisfine/poczuul:2
        - docker push sushilisfine/pocauth:2
        - docker push sushilisfine/pocnginx:2

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "ap-south-1"
  app: "resopt-docker-poc"
  env: "ResoptDockerPoc-env"
  bucket_name: "elasticbeanstalk-ap-south-1-843615263948"
  bucker_path: "resopt-docker-poc"
          
