sudo: required
services:
        - docker
script:
        - docker build -f brain-server/DockerFileDev -t sushilisfine/pocserver:4 .
        - docker build -f brain-core-api/DockerFileDev -t sushilisfine/poccore:4 .
        - docker build -f brain-zuul/DockerFileDev -t sushilisfine/poczuul:4 .
        - docker build -f brain-auth/DockerFileDev -t sushilisfine/pocauth:4 .
        - docker build -f nginx/DockerFileDev -t sushilisfine/pocnginx:4 .

        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        
        - docker push sushilisfine/pocserver:4
        - docker push sushilisfine/poccore:4
        - docker push sushilisfine/poczuul:4
        - docker push sushilisfine/pocauth:4
        - docker push sushilisfine/pocnginx:4

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "resopt-docker"
  env: "ResoptDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-843615263948"
  bucker_path: "resopt-docker-poc"
          
