version: '3.8'

services:
  sql:
    environment:
    - MYSQL_ROOT_PASSWORD=root
    #- MYSQL_DATABASE=test
    container_name: sql
    restart: always
    build:
      context: .
      dockerfile: Mysql/DockerFileDev
    ports:
      - '3306:3306'

  server:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: brain-server/DockerFileDev
    ports:
      - '8761:8761'

  zuul:
    container_name: zuul
    depends_on: 
      - server
    build:
      context: .
      dockerfile: brain-zuul/DockerFileDev
    ports:
      - '3000:3000'

  core:
    container_name: core
    depends_on: 
      - server
      - sql
    build:
      context: .
      dockerfile: brain-core-api/DockerFileDev
    ports:
      - '8009:8009'

  auth:
    container_name: auth
    depends_on: 
      - server
      - sql
    build:
      context: .
      dockerfile: brain-auth/DockerFileDev
    ports:
      - '9100:9100'

 # front:
 #   container_name: front
 #   depends_on: 
 #     - server
 #   build:
 #     context: .
 #     dockerfile: brain-frontend-style/DockerFileProd
 #   ports:
 #     - '80:80'







