spring:
      jpa:
          hibernate:
                   ddl-auto: update
                   naming:
                          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          show-sql: false
          properties:
                    hibernate:
                             format_sql: false
                             dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      datasource:
               url: jdbc:mysql://sql:3306/optimisation?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
               username: root
               password: root
               initialization-mode: always
